### ISSUE TITLE
Look at LazyContext

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/Query.jl#131]
Might be an option for a dplyr like interface. 

https://github.com/bramtayl/LazyContext.jl

**Comment by bramtayl** [comment]
Oh hi! I've already started building one at LazyQuery.jl. Take a look at master.

**Comment by davidanthoff** [comment]
Closing. There was a lot of cool stuff in LazyQuery, but I think at this point there is no actionable thing here to do.
