### ISSUE TITLE
ValuedTuples

### ISSUE THREAD

**Issue by bramtayl** [queryverse/Query.jl#143]
I've just published a package, ValuedTuples.https://github.com/bramtayl/ValuedTuples.jl. It is a different implementation of NamedTuples. It has some nice features (like type stable merging and deleting). Might come handy in the Anthoffverse if something in Base doesn't come around first.

**Comment by davidanthoff** [comment]
Cool, this looks interesting (like pretty much all the things you do!). Having a type stable merge would be super, super helpful...

But this can't get us the ``x.a`` field access syntax right? Field access is always ``v[@value b]``, with this? If so, we'd probably have to wait with using this here... But I assume the code you developed could also be made to work with the named tuples implementation in base, right? My gut feeling is that we will just have to wait for that to really square things.

**Comment by bramtayl** [comment]
Yeah I mentioned it in the NamedTuples thread in base. Yes, the field access thing is an issue though if you have suggestions for macro syntax I'd take them. It wouldn't be a problem in LazyQuery because if b occurs in the names of v it would automatically be replaced with `v[@value b]` anyway.

**Comment by bramtayl** [comment]
Also a problem which could be solved with dot overloading.

**Comment by davidanthoff** [comment]
Yes, dot overloading is the one feature I would *really* like to see in Base... It would open up so many cool things.

I could probably rewrite ``i.a`` into the ValuedTuples syntax in the various Query.jl macros, but then things would break if someone queries a source that returns ``struct`` elements of some other type...

**Comment by bramtayl** [comment]
https://github.com/bramtayl/DotOverloading.jl
