### ISSUE TITLE
Enhancement: Additional Select Operators

### ISSUE THREAD

**Issue by phillc73** [queryverse/Query.jl#164]
Coming from R and new to Julia, so perhaps missing something straightforward, but I'd like a way to perform additional operations within `@select`, pretty much ala [dplyr.](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)

Initially, I was looking for a way to de-select a single column, something like:

```Julia
using Query, DataFrames

df = DataFrame(name=["John", "Sally", "Kirk"], age=[23., 42., 59.], children=[3,5,2])

x = @from i in df begin
    @where i.age > 30. && i.children > 2
    @select i -i.age
    @collect DataFrame
end

println(x)
```
Or de-select multiple columns:

```Julia
using Query, DataFrames

df = DataFrame(name=["John", "Sally", "Kirk"], age=[23., 42., 59.], children=[3,5,2])

x = @from i in df begin
    @where i.age > 30. && i.children > 2
    @select i -{i.age, i.children}
    @collect DataFrame
end

println(x)
```
Obviously a toy example, but handy if working with a DataFrame containing many columns.

Other operators for columns such as `contains`, `starts_with` and `ends_with` also really useful for string matches on column names.

**Comment by davidanthoff** [comment]
Those things are very much on my radar, but will have to wait until julia 1.0. I need a different named tuples implementation for this to work in a performant way. The good news is that the kind of named tuple I need was merged into julia Base a while ago, so now we just need to wait until they ship 1.0 :)

**Comment by phillc73** [comment]
Great! Well, with the v1.0 feature freeze announced, hopefully it's not all that far away. Thanks.

**Comment by swt30** [comment]
Also worth mentioning: the `everything()` command that lets you re-order columns:

```R
select(df, col3, col2, everything())
# df now contains col3 then col2 then everything else
```

**Comment by davidanthoff** [comment]
This is now merged on ``master`` and documented at http://www.queryverse.org/Query.jl/dev/standalonequerycommands/.
