### ISSUE TITLE
type LineNumberNode has no field head

### ISSUE THREAD

**Issue by jcheyns** [queryverse/Query.jl#185]
when using v0.7
`using CSV,DataFrames,Query
iris = CSV.read(joinpath(Pkg.dir("DataFrames"), "test/data/iris.csv"))
@from x in iris begin
        @select get(x.Row)=>get(x.SepalWidth)
                @collect Dict
                    end
`

> ERROR: LoadError: type LineNumberNode has no field head
Stacktrace:
 [1] getproperty(::Any, ::Symbol) at .\sysimg.jl:18
 [2] (::getfield(Query, Symbol("##13#14")))(::LineNumberNode) at C:\Users\105005
08\.julia\packages\Query\VIFk\src\Query.jl:47
 [3] mapfilter(::getfield(Query, Symbol("##13#14")), ::typeof(push!), ::Array{An
y,1}, ::Array{Any,1}) at .\abstractset.jl:335
 [4] filter(::Function, ::Array{Any,1}) at .\array.jl:2356
 [5] @from(::LineNumberNode, ::Module, ::Expr, ::Expr) at C:\Users\10500508\.jul
ia\packages\Query\VIFk\src\Query.jl:47
in expression starting at REPL[43]:1
Does the LineNumberNode get removed somewhere in the macro processing?
Somehat similar to https://github.com/MikeInnes/MacroTools.jl/pull/68

**Comment by davidanthoff** [comment]
I'm working on the julia 0.7 port, but it is not yet finished, you just can't use this on 0.7 right now.

**Comment by jcheyns** [comment]
Is there a PR to track, or potentially even make some contributions?

**Comment by davidanthoff** [comment]
No, right now it is all on my hard drive. I'll try to push a branch and open a WIP PR so that you can check it out. I think I'm pretty much done, just need to fix 2-3 corner cases.

I will open up a couple of issues with ideas for new features that folks might be able to help with, getting more people to work on this would be fantastic!
