### ISSUE TITLE
Mismatch docs and exposed macros

### ISSUE THREAD

**Issue by matbesancon** [queryverse/Query.jl#187]
```
julia> Pkg.status("Query")
 - Query                         0.9.3
julia> using Query
julia> using DataFrames
julia> @select
ERROR: UndefVarError: @select not defined
julia> @collect
ERROR: UndefVarError: @collect not defined
julia> @group
ERROR: UndefVarError: @group not defined
```
Several functions seem to be used in the documentation on "stable" but not exposed
http://www.queryverse.org/Query.jl/stable/gettingstarted.html

**Comment by davidanthoff** [comment]
You can only use these inside a ``@from`` block.

There are also the [standalone commands](http://www.queryverse.org/Query.jl/stable/experimental.html), those work outside of a ``@from`` macro call.
