### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/Query.jl#194]

**Comment by leethargo** [comment]
Is this related to describing the new(?) pipe-based syntax, as shown in your JuliaCon 2018 tutorial?
I think you mentioned that you want to keep the old macros for backwards-compatibility, but prefer the new syntax.

**Comment by davidanthoff** [comment]
Probably ;) I don't really remember what this was :) I might also just have meant that the docs need to be updated for the julia 1.0 changes, and that all the doc tests need to pass again...

**Comment by davidanthoff** [comment]
Oh, and yes, I do want to give a proper treatment in the docs to the pipe style, in addition to the existing LINQ style! I don't ever want to get rid of the LINQ style queries, so I think both should just be documented as alternatives.

**Comment by leethargo** [comment]
OK, good. I also found that the pipe-based syntax is actually documented, in the last section on [Experimental Features](http://www.queryverse.org/Query.jl/stable/experimental.html).

**Comment by davidanthoff** [comment]
Ah yes, I just plan to move it into a proper section, the experimentation is over, that stuff will stay!
