### ISSUE TITLE
Eliminate {} syntax for a named tuple

### ISSUE THREAD

**Issue by lewisl** [queryverse/Query.jl#200]
Up to 6.0, using a named tuple argument in a @select statement would have required importing NamedTuple and using the @NT(a = foo, b = bar) syntax.  This should be retained for 0.6.x compatibility.

However, it seems very harmful to introduce variant syntax, essentially in violation of Julia syntax. A point was made in 0.6 to restrict {} as the containership delimiters for types.  Their use was eliminated (I believe) in constructors.  Seems wise to me.  Wise or not, the powers-that-be ruled.

Now especially that named tuples are a first class container object in Julia 0.7/1.0 and beyond the syntax can be the consistent and appealing: @project (i.name, Age=i.age).  In fact, I bet it already works with no work:  the named tuple literal is, for all the world, a named tuple.  All that remains to be done is to remove support for using {}.  Parentheses could not have worked previously as an error would result without the space or the parentheses would have been interpreted as an argument list (which might have worked had @project interpreted arguments in such fashion...).

In general, it seems unwise to invent new syntax, especially syntax that violates Julia usage in other contexts--unless you stick it into a string argument and parse apart the string--no rules there, but it is so infelicitous as to be not much of a risk of wide adoption.  In this case, there wasn't any convenient way to do it at all.  In some cases, the temptation arises to invent new syntax to save a few keystrokes.  Convenience always seems nice, but it junks up the language if new things are put in odd places.  If the inconvenience is great enough (happens) then make a change broadly to the language.

This is looking like a great package.  With some simplifications and clarifications it could gain wider usage.

**Comment by davidanthoff** [comment]
We need the ``{}`` syntax because it does more than what the base named tuple syntax does. In particular, ``{i.foo, i.bar}`` is equivalent to ``(foo=i.foo, bar=i.bar)``, which is an important construct for Query.jl that originates from C#.

Note also another important point here: I'm not giving a new semantics to syntax that would be valid outside the Query macros.

In general, Query.jl is in a stable phase, i.e. the bar for making any breaking change is very, very high. I have a long list of things to make it easier to use, but all of them are non-breaking.

**Comment by lewisl** [comment]
I did realize you are doing more than just creating a named tuple.  What happens if you put a named tuple there?  Are the new column names not set?

**Comment by davidanthoff** [comment]
Something like ``(i.foo, bar2=i.bar)`` is invalid syntax, and ``(i.foo, i.bar)`` would create a tuple and the column names are lost.
