### ISSUE TITLE
Error when a dataframe has an entire column of missing values

### ISSUE THREAD

**Issue by pstaabp** [queryverse/Query.jl#205]
If I create a dataframe with an entire column of missing values, like:

```
df = DataFrame(A=[1,2,3],B=["hi","there",missing],C=[missing,missing,missing])
```

and the do a simple filter:
```
x=@from row in df begin
  @where row.A == 3
  @select row
  @collect DataFrame
end
```

then the following error occurs:
```
UndefVarError: T not defined

Stacktrace:
 [1] datavaluetype(::Type{Missing}) at /Users/XXX/.julia/packages/Tables/vsNyh/src/datavalues.jl:7
 [2] datavaluetype(::Tables.Schema{(:A, :B, :C),Tuple{Int64,Union{Missing, String},Missing}}) at /Users/XXX/.julia/packages/Tables/vsNyh/src/query.jl:10
 [3] datavaluerows(::DataFrame) at /Users/XXX/.julia/packages/Tables/vsNyh/src/datavalues.jl:20
 [4] getiterator at /Users/XXX/.julia/packages/DataFrames/VC5qi/src/other/tables.jl:40 [inlined]
 [5] query(::DataFrame) at /Users/XXX/.julia/packages/QueryOperators/VfF5B/src/source_iterable.jl:7
 [6] top-level scope at In[106]:1
```

It appears diving into the code that the `datavaluetype` function is expecting a `Union{SOME_TYPE_HERE,Missing}` type and I think that df[:A] is type `Missing`, since
```
eltypes(df)
```
returns
```
3-element Array{Type,1}:
 Int64                 
 Union{Missing, String}
 Missing
```

Although I have found a work-around to drop all of the columns of my dataframe with type Missing (since there's no helpful info there), it seems such a dataframe shouldn't give an error.

**Comment by davidanthoff** [comment]
Thanks for reporting this! This is a bug in [Tables.jl](https://github.com/JuliaData/Tables.jl). The Queryverse integration for [DataFrames.jl](https://github.com/JuliaData/DataFrames.jl) recently moved from [IterableTables.jl](https://github.com/queryverse/IterableTables.jl) to [Tables.jl](https://github.com/JuliaData/Tables.jl). The old integration in [IterableTables.jl](https://github.com/queryverse/IterableTables.jl) handles this case correctly, so one short-term solution would be to pin [DataFrames.jl](https://github.com/JuliaData/DataFrames.jl) to v0.13.1 until this is fixed.

CC @quinnj

**Comment by davidanthoff** [comment]
I'm working on a PR.

**Comment by quinnj** [comment]
Fix merged and tagged a new release: https://github.com/JuliaLang/METADATA.jl/pull/18579
