### ISSUE TITLE
Add documentation for @select, @rename and @mutate

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/Query.jl#221]
For now we can just add a sub section to experimental. @davidanthoff  might also find the time to rearrange that part of the documentation, in which case he will update this issue here to indicate where it should go instead.

**Comment by davidanthoff** [comment]
I rearranged docs, so now it should go into this file: https://github.com/queryverse/Query.jl/blob/master/docs/src/standalonequerycommands.md

**Comment by tnederlof** [comment]
Hi @davidanthoff I am very excited to see the start of @select @rename and @mutate and I would like to help contributing documentation as I learn them. I will read through the rest of the documentation and experiment with all of the query commands to get an overall feel then take a shot at some text for these newer experimental macros.
I am new to Julia and havent contributed much publicly on github but looking to change both of those things. I have a lot of experience using SQL and dplyr type tools in other languages so hopefully, I can add value.
Please let me know if there are specific things I should keep in mind!

**Comment by davidanthoff** [comment]
@tnederlof That would be fantastic, any PRs would be super welcome!

@Yijia-Chen and @TonyLianLong implemented these new features and our original plan was that they would also write the documentation, but I'm sure they would be thrilled if you wanted to take that on instead, then they can write some more core code for the package!

I would suggest that the three of you self-organize who would write the documentation for these new commands, and if @tnederlof does it, maybe @Yijia-Chen and @TonyLianLong can help out with explanations etc.

There is one caveat: we hope to ship a new version of Query.jl by 12/14, and this is a blocking issue for that. So if you, @tnederlof, don't think you will have it by then, it might be best if we do it in-house.

But for now, lets hope this works out, we would really welcome your help!!

**Comment by tnederlof** [comment]
Thank you for letting me know about the ship deadline, nothing like a deadline to get things done, it truly doest help often. @Yijia-Chen and @TonyLianLong, would it help if I created a draft (just taking a stab at what I can tell is the current extent of the functionality, ignoring the stuff that currently has issues outstanding like ranges, etc) and run it by you two? I could do that within the next week but if its easier for you all to just do it in house and get it done sooner then feel free to let me know, I wont take it personally and will help on future things once you ship the new version.

**Comment by Yijia-Chen** [comment]
@tnederlof Thanks for offering to help, and sorry for not getting back to you earlier. We're hoping to complete this version by the 14th as @davidanthoff mentioned, so at this point I will just take care of the documentation. Please check back later though when we have made new progress, and we hope you can help then!

**Comment by tnederlof** [comment]
Thank you @Yijia-Chen no worries, I am still learning Julia and have plenty to explore (including going through package internals to get familiar). I will do that and see where I can help (fix issues, enhance docs) post the Dec 14th release.
