### ISSUE TITLE
add a @unique macro

### ISSUE THREAD

**Issue by catethos** [queryverse/Query.jl#234]
It will be good if we can do something like 
```
table |>
   @unique(:column)
```
similar to `distinct` in `dplyr`

**Comment by davidanthoff** [comment]
I think the syntax for us would be ``@unique(_.colName)``. Then it would all work with non-table sources etc.

One slightly annoying thing is that ``unique`` in base has a version that combines projection with it. I'm not a fan of that, so I think we'll just do that differently here... If one wants to also map, one can just combine things with a pipe operator.
