### ISSUE TITLE
More examples for the syntax parts of the documentation

### ISSUE THREAD

**Issue by cormullion** [queryverse/Query.jl#271]
This is an excellent package! Here's a suggestion for the documentation...

I find learning a new language is easier if there's a kind of phrase book to accompany the reference material (grammars, dictionaries, etc.). Perhaps from the summit of the Queryverse the syntax looks easy and intuitive — but down here on the nursery slopes I found it harder to get the hang of. This might be partly due to the wild error messages (miss a single character, and you'll see pages of world-age errors) but mainly I think because the syntax is slightly different from standard Julia. (It may be more familiar to users of other packages, of course.) 

I spent a bit of time compiling a list of very basic, simple examples that some other new, and possibly less technical, users might appreciate. I think it would make a nice addition to the docs.

==============================================================
# The standalone query syntax

The standalone query syntax provides a set of commands starting with `@` that can be combined into a sequence or pipeline, using the pipe (`|>`) operator. Commands include:

- selection and filtering: `@select` `@filter` `@take` `@drop` `@unique`  

- mapping: `@map` `@mapmany`

- grouping and joining: `@groupby` `@orderby` `@groupjoin` `@join`

- other: `@rename` `@mutate`

Here's a very simple example. Create a simple DataFrame of fruits:

```
df = DataFrame(
    fruit    =  ["Apple", "Banana", "Cherry"],
    amount   =  [2, 6, 1000],
    price    =  [1.2, 2.0, 0.4],
    isyellow =  [false, true, false])

3×4 DataFrame
│ Row │ fruit  │ amount │ price   │ isyellow │
│     │ String │ Int64  │ Float64 │ Bool     │
├─────┼────────┼────────┼─────────┼──────────┤
│ 1   │ Apple  │ 2      │ 1.2     │ 0        │
│ 2   │ Banana │ 6      │ 2.0     │ 1        │
│ 3   │ Cherry │ 1000   │ 0.4     │ 0        │
```

A query can pipe this dataframe through one or more commands. First it's passed to the `@select` command to select two of the four columns, then through the `@filter` command to keep just the rows that satisfy a condition, i.e. where the price is greater than 1.5 ($€£).

```
df |> @select(:fruit, :price) |> @filter(x -> x.price > 1.5) |> DataFrame

1×2 DataFrame
│ Row │ fruit  │ price   │
│     │ String │ Float64 │
├─────┼────────┼─────────┤
│ 1   │ Banana │ 2.0     │
```

In the following examples, we'll use the same DataFrame as the data source, as `df` (Although the examples all feature a simple DataFrame, similar queries can work on any of the data sources listed in section [Data Sources].)

## Selection: @select

Use `@select` to pass one or more columns from the DataFrame to the next part of the pipeline. Supply one or more clauses: each successive clause builds or modifies the selection that is passed to the next stage of the pipeline.

You can select columns by name, by position, or with a predicate function.

```
df |> @select(:fruit) |> DataFrame

3×1 DataFrame
│ Row │ fruit  │
│     │ String │
├─────┼────────┤
│ 1   │ Apple  │
│ 2   │ Banana │
│ 3   │ Cherry │
```

Select two columns by name. Each clause specifies a column:

```
df |> @select(:fruit, :amount) |> DataFrame

3×2 DataFrame
│ Row │ fruit  │ amount │
│     │ String │ Int64  │
├─────┼────────┼────────┤
│ 1   │ Apple  │ 2      │
│ 2   │ Banana │ 6      │
│ 3   │ Cherry │ 1000   │
```

Select all columns, but then deselect one of them by name:

```
df |> @select(-:amount) |> DataFrame

3×3 DataFrame
│ Row │ fruit  │ price   │ isyellow │
│     │ String │ Float64 │ Bool     │
├─────┼────────┼─────────┼──────────┤
│ 1   │ Apple  │ 1.2     │ 0        │
│ 2   │ Banana │ 2.0     │ 1        │
│ 3   │ Cherry │ 0.4     │ 0        │
```

Select all but two named columns. Use `-` and `+` to remove or add columns to the selection.

```
df |> @select(-:amount, -:isyellow) |> DataFrame

3×2 DataFrame
│ Row │ fruit  │ price   │
│     │ String │ Float64 │
├─────┼────────┼─────────┤
│ 1   │ Apple  │ 1.2     │
│ 2   │ Banana │ 2.0     │
│ 3   │ Cherry │ 0.4     │

```

You can select columns by number (position). For example, select columns 1 to 4 then deselect column 2

```
df |> @select(1:4, -2) |> DataFrame

3×3 DataFrame
│ Row │ fruit  │ price   │ isyellow │
│     │ String │ Float64 │ Bool     │
├─────┼────────┼─────────┼──────────┤
│ 1   │ Apple  │ 1.2     │ 0        │
│ 2   │ Banana │ 2.0     │ 1        │
│ 3   │ Cherry │ 0.4     │ 0        │
```

It's possible to use a predicate function to select columns. Select a column that starts with a string:

```
df |> @select(startswith("fru")) |> DataFrame

3×1 DataFrame
│ Row │ fruit  │
│     │ String │
├─────┼────────┤
│ 1   │ Apple  │
│ 2   │ Banana │
│ 3   │ Cherry │

```
Select columns that start with either of two strings:

```
df |> @select(startswith("fru"), startswith("amo")) |> DataFrame

3×2 DataFrame
│ Row │ fruit  │ amount │
│     │ String │ Int64  │
├─────┼────────┼────────┤
│ 1   │ Apple  │ 2      │
│ 2   │ Banana │ 6      │
│ 3   │ Cherry │ 1000   │

```
Select all columns whose names contain a particular string:
```
df |> @select(occursin("i")) |> DataFrame

3×3 DataFrame
│ Row │ fruit  │ price   │ isyellow │
│     │ String │ Float64 │ Bool     │
├─────┼────────┼─────────┼──────────┤
│ 1   │ Apple  │ 1.2     │ 0        │
│ 2   │ Banana │ 2.0     │ 1        │
│ 3   │ Cherry │ 0.4     │ 0        │
```

Notice that you can, in certain cases, use the alternative format for supplying arguments to macros, ie using spaces rather than parentheses and commas:

```
df |> @select occursin("i") startswith("fru") |> DataFrame

3x3 query result
fruit  │ price │ isyellow
───────┼───────┼─────────
Apple  │ 1.2   │ false   
Banana │ 2.0   │ true    
Cherry │ 0.4   │ false   
```

Select column names that don't end with a particular string (so here the `:amount` column isn't selected)

```
df |> @select(!endswith("t")) |> DataFrame

3×2 DataFrame
│ Row │ price   │ isyellow │
│     │ Float64 │ Bool     │
├─────┼─────────┼──────────┤
│ 1   │ 1.2     │ 0        │
│ 2   │ 2.0     │ 1        │
│ 3   │ 0.4     │ 0        │

```

To deselect the `:amount` column, then add column 1:

```
df |> @select(!endswith("t"), 1) |> DataFrame

3×3 DataFrame
│ Row │ price   │ isyellow │ fruit  │
│     │ Float64 │ Bool     │ String │
├─────┼─────────┼──────────┼────────┤
│ 1   │ 1.2     │ 0        │ Apple  │
│ 2   │ 2.0     │ 1        │ Banana │
│ 3   │ 0.4     │ 0        │ Cherry │
```

Select columns 1 and 3, but not in that order:

```
df |> @select(3, 1) |> DataFrame

3×2 DataFrame
│ Row │ price   │ fruit  │
│     │ Float64 │ String │
├─────┼─────────┼────────┤
│ 1   │ 1.2     │ Apple  │
│ 2   │ 2.0     │ Banana │
│ 3   │ 0.4     │ Cherry │
```

Select two columns by supplying two string:

```
df |> @select(occursin("ui"), occursin("ice")) |> DataFrame

3×2 DataFrame
│ Row │ fruit  │ price   │
│     │ String │ Float64 │
├─────┼────────┼─────────┤
│ 1   │ Apple  │ 1.2     │
│ 2   │ Banana │ 2.0     │
│ 3   │ Cherry │ 0.4     │

```

Select all columns containing one string but then remove any that contain another string

```
df |> @select(occursin("i"), -occursin("r")) |> DataFrame

3×1 DataFrame
│ Row │ isyellow │
│     │ Bool     │
├─────┼──────────┤
│ 1   │ 0        │
│ 2   │ 1        │
│ 3   │ 0        │
```

## Filtering: @filter

Use the `@filter` operation to filter (which, as elsewhere in Julia, means "keep") the source, using an anonymous function returning true or false. If the function returns true, the item is kept.

In these examples, the `@filter` operation receives all the rows of a dataframe `df`:

Keep all rows where the value for `:amount` is greater than 2

```
df |> @filter(col -> col.amount > 2) |> DataFrame

2×4 DataFrame
│ Row │ fruit  │ amount │ price   │ isyellow │
│     │ String │ Int64  │ Float64 │ Bool     │
├─────┼────────┼────────┼─────────┼──────────┤
│ 1   │ Banana │ 6      │ 2.0     │ 1        │
│ 2   │ Cherry │ 1000   │ 0.4     │ 0   

```

Keep all rows where the name of the fruit starts with a consonant. This uses a regular expression.

```
df |> @filter(col -> !startswith(col.fruit, r"A|E|I|O|U")) |> DataFrame

2×4 DataFrame
│ Row │ fruit  │ amount │ price   │ isyellow │
│     │ String │ Int64  │ Float64 │ Bool     │
├─────┼────────┼────────┼─────────┼──────────┤
│ 1   │ Banana │ 6      │ 2.0     │ 1        │
│ 2   │ Cherry │ 1000   │ 0.4     │ 0       
```

Keep all rows where the amount is greater than 10:

```
df |> @filter(col -> col.amount > 10) |> DataFrame

1×4 DataFrame
│ Row │ fruit  │ amount │ price   │ isyellow │
│     │ String │ Int64  │ Float64 │ Bool     │
├─────┼────────┼────────┼─────────┼──────────┤
│ 1   │ Cherry │ 1000   │ 0.4     │ 0      
```

There's a shorter (marked elsewhere in the documentation as "experimental") syntax available which compresses an anonymous function call into a single underscore, i.e. where `_` means `_ -> _`. This next example keep all rows where the amount is greater than 10:

```
df |> @filter(_.amount > 10) |> DataFrame

1×4 DataFrame
│ Row │ fruit  │ amount │ price   │ isyellow │
│     │ String │ Int64  │ Float64 │ Bool     │
├─────┼────────┼────────┼─────────┼──────────┤
│ 1   │ Cherry │ 1000   │ 0.4     │ 0        
```

#### Combining @filter and @select

Typically you might want to pass the output of the `@filter` command to a `@select` command:

```
df |> @filter(col -> col.amount > 2) |> @select(:fruit, :price) |> DataFrame

2×2 DataFrame
│ Row │ fruit  │ price   │
│     │ String │ Float64 │
├─────┼────────┼─────────┤
│ 1   │ Banana │ 2.0     │
│ 2   │ Cherry │ 0.4     │
```

Obviously, the order matters. You can't filter by amount if you haven't selected that column.

```
df |> @select(:fruit, :price) |> @filter(col -> col.price > 1.2)  |> DataFrame

1×2 DataFrame
│ Row │ fruit  │ price   │
│     │ String │ Float64 │
├─────┼────────┼─────────┤
│ 1   │ Banana │ 2.0     │
```

## More selection: `@unique` `@take` `@drop`   

`@unique` passes only the unique rows through to the next command.

```
push!(df, df[1, :])

4×4 DataFrame
│ Row │ fruit  │ amount │ price   │ isyellow │
│     │ String │ Int64  │ Float64 │ Bool     │
├─────┼────────┼────────┼─────────┼──────────┤
│ 1   │ Apple  │ 2      │ 1.2     │ 0        │
│ 2   │ Banana │ 6      │ 2.0     │ 1        │
│ 3   │ Cherry │ 1000   │ 0.4     │ 0        │
│ 4   │ Apple  │ 2      │ 1.2     │ 0        │

df |> @unique() |> DataFrame

3×4 DataFrame
│ Row │ fruit  │ amount │ price   │ isyellow │
│     │ String │ Int64  │ Float64 │ Bool     │
├─────┼────────┼────────┼─────────┼──────────┤
│ 1   │ Apple  │ 2      │ 1.2     │ 0        │
│ 2   │ Banana │ 6      │ 2.0     │ 1        │
│ 3   │ Cherry │ 1000   │ 0.4     │ 0        │


df

4×4 DataFrame
│ Row │ fruit  │ amount │ price   │ isyellow │
│     │ String │ Int64  │ Float64 │ Bool     │
├─────┼────────┼────────┼─────────┼──────────┤
│ 1   │ Apple  │ 2      │ 1.2     │ 0        │
│ 2   │ Banana │ 6      │ 2.0     │ 1        │
│ 3   │ Cherry │ 1000   │ 0.4     │ 0        │
│ 4   │ Apple  │ 2      │ 1.2     │ 0        │

```

`@take(n)` selects the first `n` items from the source.

```
df |> @take(2) |> DataFrame

2×5 DataFrame
│ Row │ fruit  │ amount │ price   │ isyellow │ x5   │
│     │ String │ Int64  │ Float64 │ Bool     │ Bool │
├─────┼────────┼────────┼─────────┼──────────┼──────┤
│ 1   │ Apple  │ 2      │ 1.2     │ 0        │ 0    │
│ 2   │ Banana │ 6      │ 2.0     │ 1        │ 1    │

```

( I stopped here. Just as it was getting interesting.)

**Comment by davidanthoff** [comment]
This is absolutely awesome!! Any chance I could tempt you to put this into a PR for the docs itself? It would probably fit best [here](https://github.com/queryverse/Query.jl/blob/master/docs/src/standalonequerycommands.md)?

**Comment by cormullion** [comment]
Cool, I'll make a PR soon... (I skipped the `jldoctest`s before so I'll have to put them in :))
