### ISSUE TITLE
Use of underscore syntax in Getting Statrted without introduction

### ISSUE THREAD

**Issue by venuur** [queryverse/Query.jl#296]
The first example in the docs

http://www.queryverse.org/Query.jl/stable/gettingstarted/#Standalone-query-operators-1

uses the underscore notation for anonymous functions without introducing it. I think a one sentence explanation, or a link to the underscore documentation would be helpful.

http://www.queryverse.org/Query.jl/stable/experimental/#The-_-and-__-syntax-1

I'm going to work on a PR to add this documentation sometime in the next week or two.

**Comment by venuur** [comment]
https://github.com/queryverse/Query.jl/pull/297

Here’s the pull request. A lint CI test failed. Not sure what to do next.

**Comment by davidanthoff** [comment]
Ah, we ignore it :) I think it is a false alarm.
