### ISSUE TITLE
Feature request: allow @mutate to create new columns

### ISSUE THREAD

**Issue by ilyagr** [queryverse/Query.jl#314]
I would like the following to work:

```julia
DataFrame(bad=[1,2], good=[0, 3]) |> @mutate(
			count = _.bad + _.good,
			bad_rate = _.bad/_.count,
			bad_pct =round(_.bad_rate*100;digits=1)
		) 
```

I don't know a good way to do it currently. I created a [forum post](https://discourse.julialang.org/t/does-query-jl-have-a-good-way-to-implement-mutations-that-depend-on-each-other/44643) asking if anyone else does.

**Comment by ilyagr** [comment]
It seems that `mutate` can create new columns as in [this example](https://discourse.julialang.org/t/does-query-jl-have-a-good-way-to-implement-mutations-that-depend-on-each-other/44643/3), but it [cannot handle interdependent mutations](https://discourse.julialang.org/t/query-mutate-weirdness-bug/44642/2) despite the documentation suggesting it might.

**Comment by OkonSamuel** [comment]
sorry to intrude here. But shouldn't this be closed?
