### ISSUE TITLE
Method API

### ISSUE THREAD

**Issue by davidanthoff** [queryverse/Query.jl#72]
I've started to add some simple methods based APIs. For example one can now do something like this:

``` julia
df = DataFrame(a=[1,2,3,4])
Query.@where(df, i->i.a >3)
```

The `@where` macro is not exported at this point because it is an experimental API, so one has to use the module name to access it. Currently this will return an iterator of `NamedTuple`s, so if one wants to get a `DataFrame` instead, one has to write:

``` julia
collect(Query.@where(df, i->i.a>3), DataFrame)
```

I should soon be able to make this work instead:

``` julia
DataFrame(Query.@where(df, i->i.a >3))
```

But in any case, right now one always has to specify the data type one wants to materialize into.

One question is: is that a good idea?

**Comment by ExpandingMan** [comment]
Thanks, will check this out.

My first concern is whether rebuilding `DataFrame`s all the time has a performance penalty, but I haven't looked into how Query.jl works yet so I don't really know what I'm talking about.

I'll post more when I've done some experimenting.

**Comment by davidanthoff** [comment]
Closing, as this has now been part of Query for a long time.
